### ISSUE TITLE
Failed to set SAPwd - Convert property 'SAPwd' value from type 'STRING' to type 'INSTANCE'

### ISSUE THREAD

**Issue by hanssonsebastian** [kkolk/mssql#2]
Hi, I'm having trouble to set the sa password for my SQL Express 2016 installation. 

I understand that SAPwd requires PSCredential instead of String, but how do I get that to work?

### "Convert property 'SAPwd' value from type 'STRING' to type 'INSTANCE'

```
- name: Install SQL Express 2016
  win_dsc:
     resource_name: SqlSetup
     Action: Install
     SourcePath: "{{ mssql_installation_path }}\\Media"
     InstanceName: "{{ mssql_instance_name }}"
     InstanceDir: "{{ mssql_instance_path }}"
     InstallSQLDataDir: "{{ mssql_sqlinstalldata_path }}"
     SQLUserDBDir: "{{ mssql_sqluserdata_path }}"
     SQLUserDBLogDir: "{{ mssql_sqluserlog_path }}"
     SQLTempDBDir: "{{ mssql_sqltempDB_path }}"
     SQLTempDBLogDir: "{{ mssql_sqltempDBlog_path }}"
     SQLBACKUPDIR: "{{ mssql_sqlbackup_path }}"
     Features: "{{ mssql_features }}"
     SQLCollation: "{{ mssql_collation }}"
     BrowserSvcStartupType: "{{ mssql_browsersvc_mode }}"
     SuppressReboot: "{{ mssql_suppress_reboot }}"
     SecurityMode: "{{ mssql_security_mode }}"
     SAPwd: Mypassword
```

**Comment by hanssonsebastian** [comment]
Seems that I just needed to add _username and _password acording to the win_dsc.ps1 module.

SAPwd_Username:
SAPwd_Password:

**Comment by kkolk** [comment]
I see, so this was an issue when mixed-mode auth was enabled?

**Comment by hanssonsebastian** [comment]
Yes it was, but adding this made it work :)

SAPwd_Username: sa 
SAPwd_Password: Mypassword

**Comment by gstorme** [comment]
Could you post your full win_dsc with how you made this work please?
When I add these I get:

```
Property SAPwd_Username in resource SQLSetup is not a valid property
Property SAPwd_Password in resource SQLSetup is not a valid property
```

**Comment by gstorme** [comment]
Never mind, it works after replacing SAPwd with those 2 parameters

**Comment by taosun** [comment]
> Never mind, it works after replacing SAPwd with those 2 parameters

Would you mind posting your fix? I am still getting SAPwd_xxxxx is not a valid property error

`- name: Install SQL Server with Product ID
  win_dsc:
    resource_name: SqlSetup
    InstanceName: "{{ item.instance_name }}"
    Features: SQLENGINE
    SQLCollation: "{{ item.instance_collation }}"
    SQLSvcAccount_username: "{{ item.svcaccount }}"
    SQLSvcAccount_password: "{{ item.svcpassword }}"
    SQLSysAdminAccounts: "{{ item.svcaccount }}"
    InstanceDir: "{{ item.instance_dir }}"
    InstallSQLDataDir: "{{ item.installdb_path }}"
    SQLUserDBDir: "{{ item.userldb_path }}"
    SQLUserDBLogDir: "{{ item.userdblog_path }}"
    SQLTempDBDir: "{{ item.tempdb_path }}"
    SQLTempDBLogDir: "{{ item.tempdblog_path }}"
    SQLBackupDir: "{{ item.backup_path }}"
    SourcePath: "{{ disk_image_out.results[0].mount_path }}"
    UpdateEnabled: False
    ForceReboot: False
    ProductKey: "{{ item.productkey }}"
    SECURITYMODE: SQL
    #SAPWD: 'Password'
    SAPwd_Username: sa
    SAPwd_Password: Password
  with_items:
    - "{{ rl_mssql_instances }}"`

**Comment by taosun** [comment]
Would you mind posting your fix? I am still getting SAPwd_xxxxx is not a valid property error


[new 2.txt](https://github.com/kkolk/mssql/files/3403388/new.2.txt)

**Comment by taosun** [comment]
`- name: Install SQL Server with Product ID
  win_dsc:
    resource_name: SqlSetup
    InstanceName: "{{ item.instance_name }}"
    Features: SQLENGINE
    SQLCollation: "{{ item.instance_collation }}"
    SQLSvcAccount_username: "{{ item.svcaccount }}"
    SQLSvcAccount_password: "{{ item.svcpassword }}"
    SQLSysAdminAccounts: "{{ item.svcaccount }}"
    InstanceDir: "{{ item.instance_dir }}"
    InstallSQLDataDir: "{{ item.installdb_path }}"
    SQLUserDBDir: "{{ item.userldb_path }}"
    SQLUserDBLogDir: "{{ item.userdblog_path }}"
    SQLTempDBDir: "{{ item.tempdb_path }}"
    SQLTempDBLogDir: "{{ item.tempdblog_path }}"
    SQLBackupDir: "{{ item.backup_path }}"
    SourcePath: "{{ disk_image_out.results[0].mount_path }}"
    UpdateEnabled: False
    ForceReboot: False
    ProductKey: "{{ item.productkey }}"
    SECURITYMODE: SQL
    #SAPWD: 'Password'
    SAPwd_Username: sa
    SAPwd_Password: Password
  with_items:
    - "{{ rl_mssql_instances }}"
`

**Comment by taosun** [comment]
> Never mind, it works after replacing SAPwd with those 2 parameters
Do you mind sharing your lines as I am still seeing the same error (not a property) as you saw. Many thanks

   SECURITYMODE: SQL
    #SAPWD: 'Password'
    SAPwd_Username: sa
    SAPwd_Password: Password

**Comment by gstorme** [comment]
```
- name: Install SQL Server
  win_dsc:
    resource_name: SQLSetup
    Action: Install
    UpdateEnabled: True
    SecurityMode: SQL
    SAPwd_username: sa
    SAPwd_password: "{{ sql_sa_pwd }}"
    ...
```
