### ISSUE TITLE
Fails on Azure windows server 2016 SP2

### ISSUE THREAD

**Issue by mbejda** [kkolk/mssql#3]
*Error*

fatal: [23.96.110.108]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname dc01: Name or service not known", "unreachable": true}

```text
ansible-playbook playbook.yml -i ./hosts --tags "mssql"

PLAY [SQL Server] *************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************
ok: [23.96.110.108]

TASK [kkolk.mssql : Powershell | Check for SQLServer DSC Powershell module] ***************************************************************************************************************************
ok: [23.96.110.108]

TASK [kkolk.mssql : Powershell | Check for Storage DSC Powershell module] *****************************************************************************************************************************
ok: [23.96.110.108]

TASK [kkolk.mssql : Powershell | Check for ServerManager Powershell module] ***************************************************************************************************************************
ok: [23.96.110.108]

TASK [kkolk.mssql : Powershell | Ensure that DBA Tools module is present] *****************************************************************************************************************************
ok: [23.96.110.108]

TASK [kkolk.mssql : Powershell | Check for xNetworking Powershell module] *****************************************************************************************************************************
ok: [23.96.110.108]

TASK [kkolk.mssql : Windows | Install .NET Framework Core] ********************************************************************************************************************************************
ok: [23.96.110.108]

TASK [kkolk.mssql : Windows | Install .NET Framework 3.5] *********************************************************************************************************************************************
ok: [23.96.110.108]

TASK [kkolk.mssql : Windows | Install .NET Framework 4.5 Features] ************************************************************************************************************************************
ok: [23.96.110.108]

TASK [kkolk.mssql : Windows | Install Windows Process Activation Service] *****************************************************************************************************************************
ok: [23.96.110.108]

TASK [kkolk.mssql : Active Directory | Ensure SQL Service account is present] *************************************************************************************************************************
fatal: [23.96.110.108]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname dc01: Name or service not known", "unreachable": true}

PLAY RECAP ********************************************************************************************************************************************************************************************
23.96.110.108              : ok=10   changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0
```

When I login to the server and ping dc01 it response back just fine.

**Comment by kkolk** [comment]
That task is being delegated to the domain controller, which means the host you are running Ansible on has to be able to connect to and run it on the DC. 

```
- name: Active Directory | Ensure SQL Agent Service account is present
  win_domain_user:
    name: "{{ mssql_agentsvc_account | regex_search('[^\\\\]*$') }}"
    firstname: "{{ mssql_instance_name }}"
    surname: AgentSvc
    password: "{{ mssql_agentsvc_account_pass }}"
    password_never_expires: yes
    user_cannot_change_password: yes
    description: "SQL Agent service account for {{ inventory_hostname }}\\{{ mssql_instance_name }}"
    state: present
    path: "{{ mssql_base_ldap_path }}"
    groups:
      - Domain Users
  delegate_to: "{{ domain_controller }}"
  tags: service_account
```

Is DC01 setup to accept SSH connections?  It should be in your inventory otherwise and setup to receive WinRM/etc.   Making sure it's in the inventory and you can do something basic on it let retrieving facts should solve this.
